### ISSUE TITLE
help.php erstellen

### ISSUE THREAD

**Issue by phoebusryan** [FriendsOfREDAXO/minify#1]

**Comment by gharlan** [comment]
Vor allem die README.md fehlt. ;)
help.php finde ich gar nicht mal so wichtig, wenn die README gut ist, denn R5.2 zeigt ja die README an, wenn keine help.php vorhanden ist.

**Comment by phoebusryan** [comment]
Ja, daran muss ich mich erst gewöhnen. Wird in der Addonliste bei Klick auf das Fragezeichen auf die Readme angezeigt wenn es kein Helpfile gibt?

**Comment by gharlan** [comment]
Ja, das ist ja die einzige Stelle bisher, wo die help.php eingebunden wird, genau um das Fragezeichen geht es.

**Comment by phoebusryan** [comment]
Okay, ja grundsätzlich könnte ich dann bei allen Addons die help.php durch die readme ersetzen. Dann müsste ich nicht alles doppelt pflegen. :-)

**Comment by staabm** [comment]
> Okay, ja grundsätzlich könnte ich dann bei allen Addons die help.php durch die readme ersetzen. Dann müsste ich nicht alles doppelt pflegen. :-)

das war der hintergedanke des features ;-)
