### ISSUE TITLE
async-Attribute für javascript

### ISSUE THREAD

**Issue by akuehnis** [FriendsOfREDAXO/minify#10]
Bei der Ausgabe eines Javascript-Sets wäre ein async-Attribut angenehm, damit Google Insight zufrieden gestellt werden kann. 

Vorschlag: Attribute zulassen im Ausgabe-String:
REX_MINIFY[type=js set=default attributes='async']

Oder direkt in der Datenbank.

**Comment by phoebusryan** [comment]
Die Idee finde ich gut. Ich würds allerdings analog dem CSS-Media lösen.

**Comment by phoebusryan** [comment]
Wären hier möglicherweise noch andere Attribute sinnvoll oder nur async?

**Comment by staabm** [comment]
Wir verwenden manchmal noch "onload" oder auch "defer"

**Comment by phoebusryan** [comment]
Ich bin mir gerade am überlegen, das Media-Feld zu entfernen und dafür eine Textarea für beliebige Attribute hinzuzufügen. Hier müsste einfach die Abwärtskompatiblität für das Media-Attribut gewährleistet werden. An sich wäre man aber flexibler. Was meint ihr dazu?

**Comment by akuehnis** [comment]
Fände ich flexibel und gut. Vielleicht lässt man Media noch eine Runde drin mit dem Hinweis, die Info ins neue Feld zu schreiben... oder so.

**Comment by phoebusryan** [comment]
Fixed in der neuen Version.
