### ISSUE TITLE
Less- und Sass-Compiler?

### ISSUE THREAD

**Issue by polarpixel** [FriendsOfREDAXO/minify#13]
Nur eine Frage: Was würdet Ihr davon halten, hier doch noch optional less- und sass-compiler mit einzubauen?
Ich finde minify super, auch die Art, wie man seine Sets definiert.
Aktuell wüsste ich jetzt aber nicht, wie man da noch schön mit CSS-Compilern arbeiten könnte, ohne das vorab immer lokal zu kompilieren.

**Comment by tbaddade** [comment]
`be_style` bringt einen Sass Compiler mit. Den könnte man auch im Frontend nutzen.

**Comment by polarpixel** [comment]
Ah, ok? Gibt das keine Kollision (zuerst muss be_style kompilieren, erst dann minifiziert das minify-AddOn)?

**Comment by tbaddade** [comment]
@polarpixel Das kann eher @phoebusryan beurteilen. Ich selbst habe das minify nicht im Einsatz.

**Comment by AWqxKAWERbXo** [comment]
@polarpixel genau so haben wir das jetzt im Einsatz. be_style kompiliert, minify minifiziert.

**Comment by polarpixel** [comment]
@alexplusde: Interessant, danke für den Hinweis.
Da ich keine Info zum Einsatz finde: Hast Du einen Hinweis für mich, ob/was man tun muss, um die Kompilierung auszulösen?

**Comment by AWqxKAWERbXo** [comment]
https://github.com/FriendsOfREDAXO/scss_compiler/issues/4#issuecomment-232363198

**Comment by phoebusryan** [comment]
Danke fürs klären :)

**Comment by polarpixel** [comment]
ja, vielen Dank an @alexplusde für die Hinweise.

**Comment by phoebusryan** [comment]
Das Minify-Addon nutzt nun direkt den SCSS-Compiler aus dem Core :)

**Comment by cukabeka** [comment]
kann der Compiler aus dem core auch LESS?

**Comment by phoebusryan** [comment]
nein, kann er nicht.
