### ISSUE TITLE
Fehler beim speichern

### ISSUE THREAD

**Issue by snapdragon72** [FriendsOfREDAXO/minify#14]
In der Redaxo 5.2 Version liefert ein Klick eines neuen "Sets" die Error-Message "Fehler beim speichern". Reinstallation hat nichts gebracht. Der Fehler ist (auf meinen Systemen) reproduzierbar.

**Comment by phoebusryan** [comment]
Kannst du mir mal wie Slack Zugangsdaten schicken? Dann würde ich das mal debuggen.

**Comment by snapdragon72** [comment]
editiert

**Comment by AWqxKAWERbXo** [comment]
@snapdragon72 schick bitte die Zugangsdaten über Slack oder persönlich, aber nicht hier öffentlich auf GitHub und bearbeite deine GitHub-Nachricht, sodass die Zugangsdaten weg sind.

**Comment by snapdragon72** [comment]
Sorry, wusste nicht, dass die Antwort direkt auf Github geht. Ist editiert, ich ändere das mal lieber ab ;)

**Comment by snapdragon72** [comment]
Was ist "Slack"???

**Comment by AWqxKAWERbXo** [comment]
http://www.redaxo.org/slack/

Eine Art Unternehmens-Chat, in dem schon über 100 Redaxo-Entwickler sich zu Redaxo austauschen.

**Comment by phoebusryan** [comment]
Ist erledigt.

**Comment by AWqxKAWERbXo** [comment]
danke, @phoebusryan
