### ISSUE TITLE
Ordner /assets/addons/minify/cache wird nicht angelegt...

### ISSUE THREAD

**Issue by phoebusryan** [FriendsOfREDAXO/minify#15]
...wenn nur .scss Dateien genutzt werden, da kein rex_file::put() genutzt wird

**Comment by phoebusryan** [comment]
Ich habe mit Gregor gesprochen und mit gerade an einem PR für be_style dran.

**Comment by AWqxKAWERbXo** [comment]
ach daran liegt das... ich wusste nie, wo ich das hätte einordnen sollen.

**Comment by phoebusryan** [comment]
Jep. Und das ist in 5.3 gefixt.
