### ISSUE TITLE
Sets direkt im Template per PHP definieren

### ISSUE THREAD

**Issue by ynamite** [FriendsOfREDAXO/minify#18]
Wäre toll, wenn man Sets direkt per PHP in einem Template definieren könnte, bzw. es eine Methode gäbte, um JS/CSS Dateien direkt zu kompilieren/komprimieren. 

Grund: ich arbeite, was Templates, Module usw. betrifft, am liebsten direkt im Filesystem. Wenn ich eine CSS oder JS Datei einem Set hinzufügen oder entfernen möchte, kann ich das z.Z. nur über's Redaxo Backend.

**Comment by phoebusryan** [comment]
Hm, das sollte bereits möglich sein. Ich schreib mal ein kurzes Tutorial und füge es in die Hilfedatei ein

**Comment by cukabeka** [comment]
Oh, das wäre interessant - das tutorial gibt es aber noch nicht, oder?

**Comment by AWqxKAWERbXo** [comment]
Ne, da gibt's meines Wissens noch nichts. Am besten mal @phoebusryan direkt darauf ansprechen, vlt. in Slack? Und dann ggf. hier die Lösung notieren.

**Comment by cukabeka** [comment]
Habe das jetzt übrigens so gelöst, evtl kann das ja in die readme:

		
		$minify = new minify();
		foreach ((glob(rex_path::assets()."/css/*.css")) as $css) {
			$minify->addFile("/".str_replace(rex_path::base(),"",$css), $set = "bla");
		};
		
		echo $minify->minify($type = 'css', $set = "bla");

das glob ist natürlich sehr speziell, aber die übergabe des pfades war etwas tricky und ist evtl nützlich.

**Comment by AWqxKAWERbXo** [comment]
Wir würden gerne eine backend.scss-Datei anlegen, sodass jedes Modul/Slice im REDAXO-Backend wie im frontend gerendert wird. Der Trick ist relativ einfach, aber dazu muss es möglich sein, minify auch im Backend einzusetzen.

Die PHP-Variante wäre hierbei eine Option für die boot.php, aber ich bekomme es nicht hin. @cukabeka kannst du mich da unterstützen? @phoebusryan oder kann man das Feature in minify verbauen? 

In meinen Augen wird da ein großes Manko behoben - die unschön gerenderten Module im Backend bei Low-Budget-Projekten ;)

**Comment by cukabeka** [comment]
Hi Alex, habe noch nicht ganz verstanden, was Du vor hast. Konntest Du mit dem Codeschnipsel oben was anfangen?
Ich würde gerade vermuten, dass Du in der boot.php sowas ähnliches wie den Code von 11/17 verbauen könntest und an einem EP einhängen, aber mit EPs kenne ich mich nicht aus. Hilft das etwas?

**Comment by AWqxKAWERbXo** [comment]
> Hi Alex, habe noch nicht ganz verstanden, was Du vor hast. Konntest Du mit dem Codeschnipsel oben was anfangen?

Ich möchte minify im Backend einsetzen.
