### ISSUE TITLE
SCSS im Debug-Modus kompilieren

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/minify#19]
Im Debug-Modus wird nur auf die SCSS-Datei verlinkt, diese müsste aber bereits kompiliert sein.

**Comment by phoebusryan** [comment]
Das sollte eigentlich der Fall sein. Wenn es nicht so ist, ist es ein Bug.

**Comment by phoebusryan** [comment]
Ich kann es nicht reproduzieren. Bei mir klappt das einwandfrei. Erzähl mir mal von deinem Szenario.

**Comment by AWqxKAWERbXo** [comment]
Ich merks mir und antworte mal nächste Woche dazu

**Comment by phoebusryan** [comment]
... und?

**Comment by AWqxKAWERbXo** [comment]
Wird bei Debug+Inline gar nicht ausgegeben.

**Comment by phoebusryan** [comment]
Von Inline war bisher gar nicht die Rede ;)

aber ich schaue es mir an.

**Comment by AWqxKAWERbXo** [comment]
Funktioniert (Problem vom 1. Beitrag) Weiß nicht, was das Problem damals war.
