### ISSUE TITLE
SCSS neu kompilieren, wenn sich importierte Dateien geändert haben

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/minify#20]
Ich bräuchte die Möglichkeit, dass auch Änderungen in importierten SCSS-Dateien ermittelt werden. 

Ideen:
- minify schaut direkt in das SCSS und sucht nach verlinkten SCSS-Dateien, oder
- minify bietet die Möglichkeit, einen Ordner nach Änderungen zu überwachen (ist vlt. am einfachsten), oder
- minify bietet die Möglichkeit, mit einer Checkbox im Entwicklungsmodus das SCSS fortwährend neu zu generieren.

**Comment by phoebusryan** [comment]
Hm, das sehe ich eigentlich eher im SCSS Compiler vom Core. Sonst wird das X mal programmiert, von jedem der den Compiler benötigt... Müsste mich da mal mit Gregor kurzschliessen.

**Comment by ynamite** [comment]
In meinem Addon klappt das bereits. Wenn du willst, kann ich dir den Code-Schnippsel gerne geben. 

Ich finde nicht, dass das am Compiler liegen sollte, der Compiler compiled einfach die Datei(en) die du angibst, aber die Überwachung des Ordners bzw. der Dateien liegt imo am Addon.

**Comment by phoebusryan** [comment]
Das unterstreicht meine obige Aussage "Sonst wird das X mal programmiert" aber. Wie hast du es denn gelöst?

**Comment by ynamite** [comment]
Versteh nicht was du meinst. Du musst das doch nur einmal programmieren? Oder meinst du jeder, der den Rex Compiler verwendet, muss das neu dazuprogrammieren? Kommt natürlich auf den Verwendungszweck an. Evtl. hast du recht, wenn ich weiter überlege ...

So hab ich's gelöst (ist jetzt direkt aus der Klasse kopiert, aber dürfte Sinn machen, sonst fragen):

```
$cssFileMTime = @filemtime($cssFileWithPath);
$sourceFileMTime = 0;

$path = pathinfo($sourceFileWithPath);

$iterator = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($path['dirname']), RecursiveIteratorIterator::CHILD_FIRST);
foreach ($iterator as $fileinfo) {
    if ($fileinfo->isFile()) {
        if ($fileinfo->getMTime() > $sourceFileMTime) {
            $sourceFileMTime = $fileinfo->getMTime();
        }
    }
}            

if ($cssFileMTime == false || $sourceFileMTime > $cssFileMTime) {
      // compile scss
      self::compileCSS($sourceFileWithPath, $cssFileWithPath, $sourceFileType, $vars);
}
```

**Comment by phoebusryan** [comment]
Ja ich meinte, dass es jeder selber programmieren muss. Es gibt bereits zwei minify-Addons und auch einige die den Compiler einfach so nutzen. Überall derselbe Code. Viel schöner wäre eine Lösung im be_style Addon.. da wo kompiliert wird.

**Comment by olien** [comment]
> Es gibt bereits zwei minify-Addons

Also wenn du hier auch das Plugin von out5 meinst: Das wird ja (hoffentlich bald) sterben sobald es den xOutPutFilter gibt...

**Comment by phoebusryan** [comment]
Meinte ich nicht. ich meinte mein minify und massif_minify von @ynamite

**Comment by olien** [comment]
ok. hätte mich auch gewundert. das Plugin ist ja kaum der rede wert :-)

**Comment by AWqxKAWERbXo** [comment]
Zum Topic: Wenn der Debug-Modus aktiv ist, werden die Dateien scheinbar fortlaufend neu generiert und damit auch importierte SCSS-Dateien berücksichtigt.

**Comment by eaCe** [comment]
Import wird bei mir nur in die CSS geschrieben, da ändert der Debugmode leider auch nichts :(

Das sieht dann so aus: 
`@import "compass/css3";@import "bootstrap";@import "mixins";@import "base";@import "styles";`

Mach ich was falsch oder funktioniert das einfach nicht?
