### ISSUE TITLE
Fehlermeldung, wenn nicht im Debugmodus

### ISSUE THREAD

**Issue by netzproductions** [FriendsOfREDAXO/minify#22]
Auf Redaxo 5.2.0 und PHP 7.0.11 generiert Minify folgende Fehlermeldung, wenn der Debugmodus ausgeschaltet ist:
`"Error" thrown in /path/to/site/redaxo/src/addons/minify/lib/class.minify.php on line 85
Class 'MatthiasMullie\Minify\JS' not found

#0 /path/to/site/redaxo/src/addons/minify/boot.php(59): minify->minify('js', 'JS', 'file')
#1 /path/to/site/redaxo/src/core/lib/extension.php(45): rex_package->{closure}(Object(rex_extension_point))
#2 /path/to/site/redaxo/src/core/lib/response.php(129): rex_extension::registerPoint(Object(rex_extension_point))
#3 /path/to/site/redaxo/src/addons/structure/plugins/content/boot.php(50): rex_response::sendPage('...', 1478629129)
#4 /path/to/site/redaxo/src/core/lib/extension.php(45): rex_package->{closure}(Object(rex_extension_point))
#5 /path/to/site/redaxo/src/core/frontend.php(23): rex_extension::registerPoint(Object(rex_extension_point))
#6 /path/to/site/redaxo/src/core/boot.php(105): require('/path/to/site...')
#7 /path/to/site/index.php(9): require('/path/to/site...')
#8 {main}`

**Comment by phoebusryan** [comment]
Huch, das würde bedeuten, dass der Autoloader von Redaxo nicht greift.. Kannst du mir nähere Infos geben? Zum Beispiel Redaxoversion, Addonversion etc?

**Comment by netzproductions** [comment]
Minify läuft auf v1.4.2, Redaxo auf 5.2.0.

**Comment by phoebusryan** [comment]
Hm, ich kanns nicht reproduzieren. Was hast du sonst noch für Addons installiert?

**Comment by netzproductions** [comment]
In einer anderen Redaxo5-Installation läuft Minify einwandfrei.. Die Addon-Übersicht findest Du hier: `https://www.dropbox.com/s/2whqmup1lcaj67r/addons.jpg?dl=0`

**Comment by phoebusryan** [comment]
Schwer zu sagen. Die meisten davon habe ich aber selber auch im Einsatz.

Ich würde ein Addon nach dem anderen deaktivieren und dann schauen ob es klappt. Anfangen würde ich mit quick_navigation und rex5_multiupload weil ich diese selber nicht nutze.

**Comment by AWqxKAWERbXo** [comment]
Fürs Protokoll:

Ich habe den gleichen Fehler. Eine (funktionierende!) Installation kopiert und neu hochgeladen. Keine Veränderung an den Addons oder den importierten Datenbanktabellen. Cache gelöscht, nur Domainpfad und Datenbank-Verbindung angepasst.

Einziger Unterschied: anderer Hoster.

Vielleicht hilft das beim Eingrenzen.

**Comment by DanielWeitenauer** [comment]
Hi,
bei mir tritt der Fehler auch auf. Ich habe mal in autoloader.cache nachgesehen: Die Datei mit der Klasse JS taucht in der Dateiliste auf, die Klasse jedoch nicht in der Klassen-Liste. Vielleicht passt bei der Codierung etwas nicht?

**Comment by DanielWeitenauer** [comment]
Ich habe mal testweise die Monster-Regex-Konstante aus der Klasse JS entfernt - dann wird die Klasse korrekt in den Autoloader übernommen. Anscheinend ist die Zeilenlänge für manche Systeme zu hoch.

**Comment by phoebusryan** [comment]
Hat es denn mit der Zeixhenlänge zutun? Hat das mal einer analysiert?

**Comment by phoebusryan** [comment]
Jetzt hatte ich dies auch mal. In der lokalen Umgebung mit MAMP. Speziell.

@DanielWeitenauer Welche Monster-Regex-Konstante meinst du?

**Comment by gharlan** [comment]
Wird in REDAXO 5.3 behoben sein.
Danke insbesondere an @DanielWeitenauer, es lag tatsächlich an der [langen String-Konstante](https://github.com/FriendsOfREDAXO/minify/blob/master/vendor/minify/src/JS.php#L25).

Zum Auffinden der Klassen in den Dateien nutzen wir eine Funktion aus Composer, die habe ich nun aktualisiert, und mit der neueren Variante klappt es korrekt.

**Comment by phoebusryan** [comment]
Top, danke @gharlan
