### ISSUE TITLE
tinify: Klasse für generiertes Bild einbauen.

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/minify#24]
Betrifft https://github.com/redaxo/redaxo/issues/707 und wäre klasse, wenn minify dann von Haus aus Infos über das tinifizierte Bild geben könnte, solange redaxo das nicht kann.

**Comment by phoebusryan** [comment]
Bitte was? Verstehe ich nicht. Tinyfy ist die Klasse von TinyPNG und TinyJPEG und erlaubt das optimieren von Bildern damit. Das minify-Addon erstellt einen neuen MediaManager-Effekt, der eben dies ermöglicht. Ich bin mir allerdings noch nicht sicher, ob das in das Addon rein soll oder ob es besser eigenständig sein sollte.

Jedenfalls wird das Bild ja nur optimiert; nicht resized.
