### ISSUE TITLE
Volle Verzeichnisse minifizieren

### ISSUE THREAD

**Issue by cukabeka** [FriendsOfREDAXO/minify#27]
Finde den Ansatz, extra im Backend im Addon selbst die Dateien zu definieren, sehr kompliziert, da ich beim entwickeln dann nicht einfach im editor bleiben kann, sondern ins Addon wechseln muss. 
Fände eine Variante gut, bei der das Addon selbständig das komplette angegebene Verzeichnis nach CSS/SCSS Dateien abgrast und diese dann alle minified ausgibt. Dann ist diese Einstellung nur einmal zu machen und nicht jedes mal, wenn ich sauber eine neue SCSS Datei anlege / hinzufüge.

Könnte ja recht einfach aktiv werden, sobald am Ende kein .css oder .scss als Angabe steht, sondern ein /. Dann die im Verzeichnis gefundenen Dateien als Array abarbeiten.

**Comment by AWqxKAWERbXo** [comment]
https://github.com/FriendsOfREDAXO/minify/issues/18

**Comment by phoebusryan** [comment]
Das sind zwei unterschiedliche Dinge und lässt sich nicht einfach so umsetzen. Vorallem wegen den Dependencies. Z.b. Brauchen einige Plugins jQuery, das liegt aber idealerweise in einen anderen Ordner (Vendor) und wäre dann nicht verfügbar. Die Möglichkeit direkt im
Template Files zu integrieren wie im anderen Isse ist daher Stabiler und sinnvoller.

**Comment by cukabeka** [comment]
zumindest für css wäre das super. wenn ich minify vor allem wegen des SCSS-compilers nutze, dann hilft das einbinden via template nach meinem verständnis ja nicht so viel, oder? ich würde ja einfach klassisch via HTML-tag einbinden, oder?

**Comment by phoebusryan** [comment]
Nein. Du würdest das Set via Array aufbauen und dann die Methode minify() aufrufen. Das Array kannst du dann ja immernoch bis read_dir oder glob füllen.

**Comment by cukabeka** [comment]
Ah ok danke. Kannst Du dafür bitte mal ein Beispiel für die Anwendung im Template notieren? 
    `$files = array('bootstrap.scss','meinkram.scss'); minify($files);`
So in etwa?
