### ISSUE TITLE
Ziel-Ordner aufräumen bzw immer denselben Dateinamen (zB den des Sets) verwenden

### ISSUE THREAD

**Issue by cukabeka** [FriendsOfREDAXO/minify#28]
Was mir noch zusätzlich lästiges aufgefallen ist: ich nutze minify direkt, um SASS zu CSS zu kompilieren und die Ergebnisse mit dem Layout abzugleichen. Bei jedem Reload mit geänderter Datei wird eine neue CSS Datei mit neuem Namen erzeugt. Innerhalb einer Stunde waren das bei mir >300 Dateien. 
Ich fände es hilfreich, wenn entweder die alte Version auch wieder gelöscht wird - oder noch besser: die Dateinamen, die schließlich im HTML eingefügt werden, wahlweise aus dem Setnamen resultieren.

**Comment by phoebusryan** [comment]
Lässt sich grundsätzlich sehr einfach umsetzen. Wenn man jedes mal andere Dateinamen hat, umgeht man den Browsercache. Das war der Gedanke dazu.

Ansonsten wäre ich für Dateinamen à la 'bundled.$setID.js/css'

**Comment by AWqxKAWERbXo** [comment]
Das war auch die best practice in SEOdrölfzig, sogar als htaccess-Lösung:

```
	# REWRITE RULE FOR JS/CSS VERSIONING
	RewriteRule ^(.*)\.\d{10}\.(css|js)$ $1.$2 [L]
```

D.h., man hat den Dateinamen geändert, aber nach wie vor nur in eine Datei styles.css / script.js geschrieben.

**Comment by phoebusryan** [comment]
Ich müsste es nun aus Prinzip nicht machen, weils in 'duweisstschonwas' so war. Ich machs nun aber trotzdem. Finde es nicht verkehrt.

**Comment by AWqxKAWERbXo** [comment]
Früher war eben nicht alles schlecht ;)
