### ISSUE TITLE
Debugmodus für CSS/JS trennen

### ISSUE THREAD

**Issue by phoebusryan** [FriendsOfREDAXO/minify#29]

**Comment by AWqxKAWERbXo** [comment]
evtl. auch pro set?

**Comment by phoebusryan** [comment]
Nutzt du denn mehrere Sets gleichzeitig bei einer Seite?

**Comment by AWqxKAWERbXo** [comment]
mehrere Domains via YRewrite, ja - jede Domain bekommt ein eigenes Set.

**Comment by phoebusryan** [comment]
Okay, jep. In Verbindung mit yrewrite ergibt es Sinn. In dem Falle wäre es tatsächlich sinnvoller, den Debugmodus in die Sets zu verschieben.

Danke für den Input.

**Comment by phoebusryan** [comment]
Ist nun in Version 1.7.0 drin.

**Comment by AWqxKAWERbXo** [comment]
Danke für deine aktive Entwicklung!
