### ISSUE TITLE
Englische Übersetzungen unvollständig

### ISSUE THREAD

**Issue by phoebusryan** [FriendsOfREDAXO/minify#3]

**Comment by AWqxKAWERbXo** [comment]
@schuer evtl.?

**Comment by phoebusryan** [comment]
:D Ich habe das Issue einfach überall drin. 90% ist ja übersetzt. Primär die Hilfeseite/langen Texte fehlen. Könnte ich grundsätzlich auch selber machen aber wenn jemand gerne Texte übersetzt, kann er es gerne tun. Ansonsten priorisiere ich lieber das coden.
