### ISSUE TITLE
Daten aus Ordner beziehen

### ISSUE THREAD

**Issue by marcohanke** [FriendsOfREDAXO/minify#31]
Hey Thomas,
ist es für dich denkbar, dass statt einzelner Dateien auch ein Ordner ausgewählt werden kann?
Beispiel:
Wenn ich /theme/public/assets/js/file.js und /theme/public/assets/js/file1.js eingebe bleibt alles beim alten, wenn ich /theme/public/assets/js/ eingebe, werden automatisch alle Dateien im Ordner zusammengefasst?

Bei mir ist es immer wieder so, dass ich beim entwicklen nach und nach mehr Dinge reinpacke. Die kopiere ich dann in mein js Ordner und muss anschließend den Pfad noch im Plugin hinterlegen. Wäre schön wenn das automatisiert gehen würde.

**Comment by phoebusryan** [comment]
Dies habe ich mir auch ursprünglich mal überlegt aber dann wieder verworfen aus mehreren Gründen. Der Hauptgrund war jedoch, dass die Reihenfolge der Files z.B. nicht definiert werden kann. Zum Beispiel könnte ein jQuery-Plugin vor der jQuery-Library rein geladen werden. Oder in CSS wäre das custom-File vor einem Plugin-Theme-File, sodass die eigenen Rules nicht mehr gelten etc. Alles in allem also recht mühsam.

**Comment by marcohanke** [comment]
Mhh, das mit der Reihenfolge ist tatsächlich ein Argument, schade ..

**Comment by skerbis** [comment]
Ich bin für die manuelle Eingabe wie aktuell. Man erhält so eine bessere Übersicht und kann so unterschiedliche Sets (z.B. für abweichende Templates) erstellen und so mal ein Skript weglassen.
