### ISSUE TITLE
Inline-Kommentare im JS entfernen

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/minify#39]
Beim eindampfen der Zeilenumbrüche werden `// Einzeilige Kommentare` nicht entfernt und deaktivieren dadurch den restlichen JS-Code.

**Comment by phoebusryan** [comment]
Sollte gefixt sein in der neusten Version.

**Comment by AWqxKAWERbXo** [comment]
Hab Dank!
