### ISSUE TITLE
Fatal error: Class 'MatthiasMullie\Minify\Minify\JS' not found

### ISSUE THREAD

**Issue by omphteliba** [FriendsOfREDAXO/minify#4]
Ich habe über den Installer Version 1.0 von Minify installiert und bekomme folgende Fehlermeldung, wenn ich versuche das Addon zu nutzen:

```
Fatal error: Class 'MatthiasMullie\Minify\Minify\JS' not found
```

**Comment by AWqxKAWERbXo** [comment]
```
Warning: Missing argument 1 for minify::minify(), called in /home/netsh108145/html/###/redaxo/src/addons/minify/boot.php on line 17 and defined in /home/netsh108145/html/###/redaxo/src/addons/minify/lib/class.minify.php on line 9

Fatal error: Class 'MatthiasMullie\Minify\Minify\CSS' not found in /home/netsh108145/html/###/redaxo/src/addons/minify/lib/class.minify.php on line 51

```

**Comment by phoebusryan** [comment]
Mhh, hab ich vorhin noch getestet gehabt. Schaus mir sofort an.

Edit: Gerade auf einer anderen Installation das Addon runtergeladen. Es funktioniert bei mir. Was für eine Version habt ihr? 5.2? 5.1?

Edit2: Dritte Installation getestet; keine Fehler

**Comment by AWqxKAWERbXo** [comment]
5.2, PHP 5.5

brauchst du ne Demo-Installation?

**Comment by phoebusryan** [comment]
Ja gerne

**Comment by phoebusryan** [comment]
Der Fehler tritt auf, weil die Klasse 'minify' keinen Konstruktor hat, aber initialisiert wird und es zusätzlich eine Methode 'minify' gibt. Das ist ein PHP 4 verhalten und etwas schräg, da es offensichtlich nicht überall tritt. Zudem greift der Autoloader nicht.

**Comment by omphteliba** [comment]
REDAXO 5.2.0
$ php -v
PHP 5.5.9-1ubuntu4.17 (cli) (built: May 19 2016 19:05:57)

**Comment by AWqxKAWERbXo** [comment]
Danke!

**Comment by hirbod** [comment]
Ich hab das selbe Problem, Debian Jessie, PHP 7.0.11, Redaxo 5.2.0
CSS läuft, JS nicht, selber Fehler, wie oben beschrieben.

Duplicate: #22
