### ISSUE TITLE
SCSS wird nicht neu generiert, wenn set als "inline" ausgewählt

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/minify#40]
Sollte aber so sein. Funktioniert, wenn Ausgabe als Dateien.

**Comment by phoebusryan** [comment]
Hm, ist das so? :) 

Hast du dabei "Minimieren?" aktiv?

**Comment by phoebusryan** [comment]
Ich glaube das hat sich mit dem letzten Update eh geregelt oder ?

**Comment by AWqxKAWERbXo** [comment]
das werden wir gleich in den nächsten 2-3 Tagen testen.

**Comment by AWqxKAWERbXo** [comment]
Leider nicht.

**Comment by phoebusryan** [comment]
Das funktioniert bei mir sehr gut. Kannst du mal deine Settings durchgeben?

**Comment by AWqxKAWERbXo** [comment]
Kann das ein paar Monate später inzwischen nicht mehr nachstellen... ich melde mich wieder, wenn's passiert.
