### ISSUE TITLE
Browser-Cache umgehen bei JS lädt JS grundsätzlich neu

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/minify#41]
Es wird immer ein neuer Zeitstempel angehängt, doch eigentlich sollte es der Zeitstempel der Datei, damit die Datei nur dann neu geladen wird, wenn sich eine Änderung ergeben hat.

**Comment by phoebusryan** [comment]
Das ergibt Sinn. Danke für das Issue.

**Comment by phoebusryan** [comment]
Gefixt in der neusten Version.

**Comment by AWqxKAWERbXo** [comment]
Das ist bei CSS auch noch so.

Die Funktion ergibt dann am meisten Sinn, wenn man den Zeitstempel der Datei als Get-Parameter anhängt. Wenn sich die Datei ändert, wird sie vom Browser neu geladen. Wenn sich die Datei nicht geändert hat, bleibt derselbe Zeitstempel erhalten und die Datei wird somit aus dem Browsercache geladen.

**Comment by AWqxKAWERbXo** [comment]
'tschuldige, muss ein anderes Problem gewesen sein. Läuft ordnungsgemäß.
