### ISSUE TITLE
HTML Kommentare ohne Conditionals entfernen

### ISSUE THREAD

**Issue by rkemmere** [FriendsOfREDAXO/minify#42]
Hallo, 

kann der preg_replace so angepasst werden, dass die conditionals comments erhalten bleiben?
Es wäre außerdem gut, wenn man es um eigene non-capturing groups erweitern könnte.

Ein weiteres Problem ist, das search_it nicht mit dem minify HTML läuft, da search_it eigene Tags wie **** einbaut und diese eben nicht entfernt werden dürfen.

`$content = preg_replace(['/<!--(.*)-->/Uis',"/[[:blank:]]+/"], ['',' '], str_replace(["\n","\r","\t"], '', `$content));``

Mögliche Syntax.

`)           #11:   a position not followed by "-->"
  .                 #12:   eat the following char, it's part of the comment
)*                  #13: end non-capturing group, repeat
-->                 #14: "-->"`

**Comment by phoebusryan** [comment]
Für das search_it-Problem gibt es bereits einen Pullrequest. Dem werde ich sicher bald nachgehen.

Bzgl. den Comments, das könnte man auch noch optmieren. Bitte ebenfalls als PR :)

**Comment by phoebusryan** [comment]
So, also die Unterstützung für search_it ist drin.

**Comment by rkemmere** [comment]
Super Danke!
