### ISSUE TITLE
%0D Am Ende jeder .js-Datei

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/minify#43]
Ich habe 2 JS-Sets. Setze ich beide innerhalb des head-tags ein, funktioniert alles wie gewünscht.  
Wenn ich aber ein Set kurz vor </body> setze, erhalten alle js-Urls  ein %0D am Ende , wenn ich diese nicht minimiere.

**Beispiel:** 

`<script src="/assets/navi/slidebar/navi-collapse.js%0D`

**Comment by phoebusryan** [comment]
Oh, das ist tatsächlich so. Werde ich asap fixen und updaten!

**Comment by AWqxKAWERbXo** [comment]
ist das überall gefixt? Habe heute auch das Addon in Aktion gesehen und es wurde von w3c bemängelt, dass die URL einen Zeilenumbruch angehängt hat.

**Comment by phoebusryan** [comment]
Das hätte ich jetzt behauptet :) Hast du die neuste Version? Ansonsten mal bitte die Einstellungen posten; dann schaue ich mir das gleich nochmal an.

**Comment by skerbis** [comment]
Alles gut. Und Danke noch mal :) Ich kann bestätigen, dass der Fehler behoben wurde.
