### ISSUE TITLE
debug-mode

### ISSUE THREAD

**Issue by cukabeka** [FriendsOfREDAXO/minify#45]
eine möglichkeit, die original-CSS auszugeben

		echo $minify->minify($type = 'css', $set = "bla", $debug = true);

wäre fein.

**Comment by phoebusryan** [comment]
Wofür denn genau? Die SCSS-Datei kann man ja z.B. nicht ausgeben lassen.

**Comment by cukabeka** [comment]
nee, aber dann habe ich eine möglichkeit, mich besser im code zurechtzufinden und herauszufinden, was woher kam

**Comment by phoebusryan** [comment]
Dafür kannst du ja minify auf nein setzen... pro Set sogar.

**Comment by phoebusryan** [comment]
*reminder*

**Comment by pschuchmann** [comment]
@cukabeka Der rex_compiler gibt eigentlich recht genau aus, woher ein Fehler kommt, wenn die Datei nicht kompliliert werden kann. Reicht dir das soweit? Das Issue liegt ja nun auch schon etwas. Ich mache hier zu, falls du dennoch etwas anmerken magst, bitte einfach nochmal genau den Fall darlegen und beschreiben, wie du es dir vorstellt!

**Comment by cukabeka** [comment]
Hi, @pschuchmann danke fürs Reinschauen in das Issue. Ist sogar immer noch aktuell, tatsächlich wieder seit dieser Woche. 
Ich benutze Minify immer über die API, also nicht mit den Sets im Backend. Es kommt immer wieder mal vor, dass sich beim Editieren des Themes im SCSS ein Fehler einschleicht, der den kompletten Compiler abschießt. Die minifizierte CSS Datei wird dann nicht mehr neu geschrieben. Ich kann dann aber auch nicht nachvollziehen, wo der Fehler entstanden ist, der den Compiler zu Fall bringt. 
Wie kann ich denn sehen, was rex_compiler für Fehler wirft? Falls das dort zu sehen ist, wäre toll, wenn das Logfile in Minify im Backend gezeigt wird.

**Comment by AWqxKAWERbXo** [comment]
@cukabeka kannst du das über die API mal dokumentieren?

**Comment by pschuchmann** [comment]
Ah, ok. Dann arbeitest du einfach anders mit dem Addon. Das, was ich im Regelfall mache ist mir eine scss Datei im Set anzulegen und darin die weiteren Imports zu machen. Und sobald dort irgendwo ein Fehler auftaucht, erhalte ich an der Stelle dann Dateiname und Zeile, wo der Fehler zu finden ist. Könntest du mir bitte einmal ein komplettes Beispiel hier posten, dann kann ich es besser nachvollziehen und zusehen, wie man das in den Griff bekommt.
