### ISSUE TITLE
Cache löschen

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/minify#46]
es sollte die Möglichkeit geben, die CSS/JS-Dateien auf Kommando neu zu generieren.

**Comment by phoebusryan** [comment]
Das funktioniert via System > Cache löschen. Warum sollte man das sonst wollen?

**Comment by AWqxKAWERbXo** [comment]
Nach einem minify-Update zerhaut es einem das Frontend, mit dem Cache-Löschen und einer Generierung der JS/CSS-Dateien wird dann wieder alles sauber dargestellt. Oder, wenn minify nicht erkennt, dass eben nicht die verlinkte SCSS-Datei bearbeitet wurde, sondern eine, die über @import referenziert wurde. 

Dazu jedes Mal den KOMPLETTEN Redaxo-Cache löschen?

**Comment by phoebusryan** [comment]
Ok, das ist ein Argument. PR willkommen :D

**Comment by AWqxKAWERbXo** [comment]
Liefere mir einen Ansatz :)

**Comment by phoebusryan** [comment]
Eigentlich recht easy. Ich würde einen Cache löschen Button hinzufügen analog dem Media Manager. Dieser verlinkt dann auf die 'Sets' Seite mit dem GET-Parameter 'func' = 'deleteCache'. und da dann die Files löschen. Wo sie liegen weiss man aufgrund des Konfigurations-Tabs. :-)

**Comment by phoebusryan** [comment]
Habs eingebaut und ist in der neusten Version dann drin :)

**Comment by AWqxKAWERbXo** [comment]
Danke @phoebusryan, ich konnte mich leider nicht selbst damit beschäftigen.

**Comment by phoebusryan** [comment]
Kein Ding. War ohnehin eine kleine Sache. 👍
