### ISSUE TITLE
Browsercache-Option mit filectime statt time

### ISSUE THREAD

**Issue by maxsmily** [FriendsOfREDAXO/minify#47]
Ich möchte gern den Cachebreaker bei minimize=='yes' nutzen. Bisher wird dieser jedoch mit time() gesetzt, was immer zu einem Neuladen des Assets führt. Das Asset soll sich jedoch nur dann neu laden, wenn es eine Dateiänderung gab (mit filectime), so wie es bei minimize=='no' bereits eingerichet ist.

In boot.php:

`$content = str_replace($match[0], '<link rel="stylesheet" href="'.trim($data).(($sets[0]['ignore_browsercache'] == 'yes') ? '?time='.filectime(ltrim($data, '/')) : '').'" '.((!empty($sets[0]['attributes'])) ? implode(' ', explode(PHP_EOL, $sets[0]['attributes'])) : '').'>', $content);`

Würde mich freuen, wenn das übernommen werden würde.

**Comment by IngoWinter** [comment]
`filemtime` wär passender. ohne das addon zu kennen - warum nicht grundsätzlich den assets ihre `filemtime` als parameter mitgeben?

**Comment by AWqxKAWERbXo** [comment]
Dann bitte wie bei seo42 per Dateiname+ ggf. htaccess-Anpassung und nicht per get-Parameter, diese werden bei Proxys gerne mal gekonnt ignoriert.

**Comment by IngoWinter** [comment]
@alexplusde wenn du über dateinamen oder pfad gehst, musst du auf zwingend die .htaccess oder das nginx pendant anpassen. das öffnet ein ganz neues fass voll maden ^^

**Comment by AWqxKAWERbXo** [comment]
Ich kann nicht sagen, ob sich seither was geändert hat, aber wenn man's nicht so macht, ist es auch madig: 
https://github.com/h5bp/html5-boilerplate/issues/256

**Comment by phoebusryan** [comment]
Ich nehme den ursprünglichen Vorschlag von @maxsmily mit rein.

**Comment by AWqxKAWERbXo** [comment]
Klasse! Jetzt müssen wir nach wichtigen Änderungen dem Kunden nicht mehr sagen, dass er den Browsercache löschen soll oder wir das Set umbenennen müssen. Eine echte Hilfe.

**Comment by IngoWinter** [comment]
filectime ist immer noch die falsche funktion. https://stackoverflow.com/questions/22042611/filectime-vs-filemtime-for-file-modification-time

**Comment by phoebusryan** [comment]
Ah, in der Tat wäre natürlich filemtime sinnvoller. Ich nehme es rein, setze deshalb aber nicht direkt noch ein neuer Release. Kommt dann also im nächsten Update.
