### ISSUE TITLE
Addon löscht Dateien, die nicht von Minify sind

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/minify#48]
Szenario: Nach einem Update von minify und Cache löschen werden ALLE Dateien im Cache-Ordner gelöscht. Falls dieser in einer älteren Konfiguration derselbe ist wie der Basis-Ordner - nämlich /assets/js/ bspw., dann werden darin alle Dateien Ursprungs-Dateien des Projekts gelöscht. Das ist fatal.

**Comment by phoebusryan** [comment]
Warum packst du auch Live- und Cachedaten in dasselbe Verzeichnis? :D

Aber dennoch.. ich schaus mir natürlich an.

**Comment by AWqxKAWERbXo** [comment]
Update von alten Minify-Addon-Versionen. Da war es noch zulässig und da gab es kein separates Verzeichnis.

**Comment by phoebusryan** [comment]
Er killt hier nur css/js/json Dateien, was natürlich dennoch blöd ist. Ich könnts noch weiter einschränken auf bundled.*.js/css oder compiled.*.scss ... oder hättest du hier eine bessere Idee?

**Comment by AWqxKAWERbXo** [comment]
Vielleicht einen weniger riskanten suffix: .minify.js - dann weiß man, woher es kommt. Ansonsten löst es das Problem doch soweit :)

**Comment by phoebusryan** [comment]
Ich könnte die Files speziell benennen und dann nur diese löschen. Wäre dann nicht Abwärtskompatibel aber es geht hier ja nur um Cachefiles.

**Comment by AWqxKAWERbXo** [comment]
Eben. Deswegen meine ich ja einen weniger riskanten Suffix wie `.minify.js`

**Comment by phoebusryan** [comment]
Okay, finde ich gut. Mache ich so. :-)

**Comment by pschuchmann** [comment]
Sollte mit dem letzten Release jetzt funktionieren, ich mache hier dann mal zu.

**Comment by AWqxKAWERbXo** [comment]
@pschuchmann inwiefern hat das neue Release dieses Problem gelöst?

**Comment by pschuchmann** [comment]
Mit dem neuen Release kannst du zum Einen die Cache Dateien einzeln in der Listenansicht löschen, zum Anderen werden jetzt die Sets, bzw. deren kompilierte Dateien durchlaufen, sobald du auf Cache löschen klickst.
