### ISSUE TITLE
Nur Pfad zur CSS/JS-Datei

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/minify#5]
Ich benötige den Pfad zur CSS ohne <link>-Tag. Gibt's eine einfache Möglichkeit, da ranzukommen?

**Comment by phoebusryan** [comment]
Nein, aktuell nicht. Das wird ja direkt eingefügt. Was hast du vor?

**Comment by AWqxKAWERbXo** [comment]
Kritisches CSS inline ausgeben. Ich habe einfach den Code aus der boot.php abgewandelt und für mich angepasst.

**Comment by phoebusryan** [comment]
Okay, der wird dann aber mit dem nächsten Update überschrieben.

Und was ist kritisches CSS?

**Comment by AWqxKAWERbXo** [comment]
https://www.smashingmagazine.com/2015/08/understanding-critical-css/

Ich hab den Code nicht ins Addon, sonst würde er überschrieben, ja. Aber den Code als Vorlage in mein project-Addon.

**Comment by sebimalwieder** [comment]
Wäre auch an der Lösung interessiert.

**Comment by phoebusryan** [comment]
Okay, ja grundsätzlich könnte ich eine Methode bauen, die den Namen zurückgibt. Dann kannst du damit machen was du willst.

**Comment by phoebusryan** [comment]
Also ihr möchtet die Möglichkeit, zusätzlich zu den Platzhaltern ein Set via API-Methode als Code statt File zu bekommen?

**Comment by AWqxKAWERbXo** [comment]
Dateiname hätte mir genügt, aber ja, darauf läuft es hinaus :)

vlt. reicht es, das über einen zusätzlichen Parameter lösen, bspw. `output=inline` und `output=link` (default)?

**Comment by phoebusryan** [comment]
... und bei inline würde z.b. ein style-tag statt link-tag hingesetzt werden? das wäre simpel umsetzbar

**Comment by AWqxKAWERbXo** [comment]
So würde ich mir das vorstellen. @sebastiannoell ?

**Comment by sebimalwieder** [comment]
Yes! Klingt super.

**Comment by phoebusryan** [comment]
Okay, dann werde ich das so machen. Eine Frage zur Umsetzung:
Einerseits könnte man den Platzhalter ergänzen (wie alexplusde es vorgeschlagen hat) à la 'output=inline oder output=link' ... oder aber mal legt im Backend den Outputmodus fest. Man möchte ja eigentlich nie das gleiche Set als Inline und als link haben oder?

**Comment by AWqxKAWERbXo** [comment]
Selbst wenn man es wollen würde, was eigentlich keinen Sinn ergibt, könnte man das set immer noch doppelt anlegen, um den gleichen Effekt zu bekommen. Ist mir also egal. Gegen eine Einstellung im Backend hätte ich nichts einzuwenden.

**Comment by staabm** [comment]
wenn der use-case kritisches css ist, dann macht eine einmalige stelle im backend keinen sinn (da man ja nicht-kritisches css dann als datei verlinkt und kritisches inline hat)

**Comment by phoebusryan** [comment]
Das ist schon richtig, jedoch wären kritisches und nicht-kritisches css ja zwei verschiedene Sets. Von dem her würde es dann passen.
