### ISSUE TITLE
Pfade in Inline-CSS stimmen nicht mehr

### ISSUE THREAD

**Issue by DanielWeitenauer** [FriendsOfREDAXO/minify#51]
Für das Inline-CSS müssten die Pfade im CSS relativ zur HTML-Datei angepasst werden. Minify rechnet sie nur relativ zur CSS-Ausgabedatei um.

**Comment by DanielWeitenauer** [comment]
Als Workaround scheint es zu klappen, bei der Angabe des Pfades zur generierten Datei ein leeres Feld stehen zu lassen.

**Comment by phoebusryan** [comment]
Das ist richtig. Hab dafür noch keine saubere Lösung, nur eine Idee, der ich bisher nicht nachgegangen bin. Aktuell nutze ich immer absolute Pfade im SCSS, um das Problem zu umgehen. Ich bin aber dran.

**Comment by AWqxKAWERbXo** [comment]
Wir haben uns auch damit arrangiert, absolute Pfade zu verwenden.

**Comment by AWqxKAWERbXo** [comment]
Gibt's hier noch Bedarf @DanielWeitenauer? Mehr haben sich nicht mehr gemeldet - ich habe das Addon lange schon nicht mehr im Einsatz dank HTTP/2.

**Comment by DanielWeitenauer** [comment]
Ich habe es auch schon lange nicht mehr im Einsatz und die letzten male als ich es genutzt habe, hatte ich die Minifizierung programmatisch ausgelöst. 
Mit den oben genannten Anpassungen sollte das Problem sich aber umschiffen lassen.
