### ISSUE TITLE
Problem mit Unterordner & doppelter Endung

### ISSUE THREAD

**Issue by godsdog** [FriendsOfREDAXO/minify#52]
Moin, 
nutze das Addon mit Redaxo 5.6.4 im Unterordner.
https://www.domain.de/unterordner/startseite.html

Spuckt mir im Frontend folgendes aus:
`<link rel="stylesheet" href="/resources/css/minify/bundled.css.css?time=1539870689" >`

Müsste sein:
`<link rel="stylesheet" href="/unterordner/resources/css/minify/bundled.css?time=1539870689" >`

Addon Config:
Pfad für generierte CSS-Dateien: /resources/css/minify

**Comment by godsdog** [comment]
Ok sehen gerade dass auf der Konfig Seite folgendes steht:
DocumentRoot-relativ, ohne Trailingslash

Fände es besser wenn es relativ zum Redaxo Pfad wäre. Szenario bei mir: Ich baue die Seite versteckt im Unterordner auf dem Kundenserver, so kann der Kunde den Prozess verfolgen. Danach schiebe ich alles in das Root Verzeichnis. Müsste dann in der Addon Konfig den Pfad wieder anpassen, was man schnell vergessen könnte :)

Ich habe bisher das Addon "MASSIF Minify" genutzt, da funktioniert es so, was mir sehr gut gefällt.

Das Problem mit der doppelten Dateiendung ist nach wie vor vorhanden.

**Comment by phoebusryan** [comment]
Das mit dem Ordner ist sicher etwas, woran man arbeiten kann. Aber das mit der doppelten Dateiendung ist seltsam. Was hast du für Sets?

**Comment by godsdog** [comment]
Das mit den doppelten Endungen hat sich geklärt, hatte als Set Name CSS und JS genutzt, dann ist ja klar, dass der CSS/JS doppelt in der URL vorkommt :)

Die Unterordner Problematik ist nach wie vor nicht lösbar für mich.

**Comment by 191977** [comment]
Hi,
will mich hier gerne anschließen. Habe ein Projekt mit einer redaxo-Installation in einem Unterordner. Entsprechend www.universitaet.de/institut_x/. Es lässt sich im Moment noch abfangen, indem in der config die Pfade mit /intistut_x/theme/... eingetragen werden. Dasselbe bei den Assets in den Sets. Jedoch soll die Seite demnächst zusätzlich unter einer eigenen Domain ohne Unterordner erreichbar sein, die wird dann so nicht laufen.

**Comment by AWqxKAWERbXo** [comment]
@191977 zusätzlich? Dann sollte die andere Domain dorthin weiterleiten, sonst hast du Duplicate Content und damit ein SEO-Problem.

**Comment by 191977** [comment]
Ja, wäre mir auch lieber, die wollen aber für die englische Version eine eigene Domain. 
Das Problem ist davon ja unabhängig, sind bestimmt noch andere Konstellationen denkbar, wo es relevant wird.

**Comment by AWqxKAWERbXo** [comment]
Du kannst auch dieselbe Domain nehmen, nur um das klarzustellen.

**Comment by AWqxKAWERbXo** [comment]
Da das Issue 6 Jahre nicht bearbeitet wurde, mache ich hier mal wegen der besseren Gesamtübersicht an FOR-Issues zu.
