### ISSUE TITLE
Einstellungsseite überarbeiten

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/minify#53]
Auf basis von https://redaxo.org/api/master/class-rex_config_form.html und so, dass die Eingabefelder die volle breite haben. Da fehlt sicher wieder eine form-control-Klasse irgendwo.

![image](https://user-images.githubusercontent.com/3855487/48132396-acaeb200-e293-11e8-97b0-d8e200ae8a9e.png)

**Comment by pschuchmann** [comment]
#57
