### ISSUE TITLE
SCSS kaputt?

### ISSUE THREAD

**Issue by cukabeka** [FriendsOfREDAXO/minify#55]
Hi, seit einem Update auf R5.6.4 funktioniert das Kompilieren von SCSS Dateien nicht mehr, kann das sein? Zumindest habe ich hier in einem Projekt plötzlich Probleme mit Minify und SCSS Änderungen.

**Comment by cukabeka** [comment]
Das Problem besteht weiterhin und ich habe trotz intensiven Debugging-Versuchen keinen Ansatz zur Lösung.
Egal ob ich den Compiler mit

`echo $minify->minify($type = 'css', $set = 'test',$output = 'file');`
oder 
`echo $minify->minify($type = 'css', $set = 'test',$output = 'inline');`

aufrufe, der Output im HTML ist immer:

`<link rel="stylesheet" type="text/css" href="">`

Eine Idee dazu?

**Comment by cukabeka** [comment]
OK, es scheint an einem Problem mit dem SCSS zu liegen. Habe unterschiedliche SCSS Dateien ausprobiert. Mit manchen funktioniert es. Anscheinend wirft der Parser unter bestimmten Bedinungungen keinen Error.

**Comment by schorschy** [comment]
hat sich also erledigt? @cukabeka

**Comment by pschuchmann** [comment]
Ich habe eben ein neues Release gemacht. Ich würde hier vorerst mal schließen, da das Issue doch schon relativ lange liegt und keine Rückmeldung mehr kam. Gerne mit dem neuen Release nochmal testen und Rückmeldung geben.

Gerade was SCSS Dateien angeht, hat sich seit 12/2019 einiges getan, neue Compiler Klasse im Core und hier ist nun auch ein Vendor Update durchgelaufen.
