### ISSUE TITLE
Minimieren der Dateien funktioniert nicht

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/minify#58]
Hallo,

ich habe gerade das Addon zum ersten Mal im (Test)Einsatz.
Leider funktioniert das Zusammenfassen von Dateien nicht. Sobald ich den Haken bei Minimieren meines CSS-Sets setze, erhalte ich nur diesen Fehler:
**Minifyerror: File "/media/style.css" does not exists**

Die Datei ist definitv da, denn ohne dem Haken werden mir einzelne Einbindungen ausgegeben und die Dateien können dirt aufgerufen werden:

`<link rel="stylesheet" href="\media\style.css?time=" media="screen"><link rel="stylesheet" href="\media\style-addons.css?time=" media="screen"><link rel="stylesheet" href="\media\style-mobile.css?time=" media="screen"><link rel="stylesheet" href="\media\jquery\flowplayer\skin\skin.css?time=1534765128" media="screen"><link rel="stylesheet" href="\media\jquery\slick\slick.css?time=1523965752" media="screen">`

Es scheint aber, dass beim Durchlaufen der Assets nur die letzte Datei korrekt ausgelesen wird.
Bei der Inline-Einbindung wird nämlich nur diese ausgegeben.

Ist das Problem bekannt?

Getestet mit: redaxo 5.7.1 (lokal im Xampp) und aktuellster minify-Version

**Comment by iceman-fx** [comment]
Problem gefunden...
...das Addon hat mir meine Dateien gelöscht, da ich als Zielordner den Pfad der Quelldateien angegeben hatte.

Anscheinend ist dieses verhalten noch nicht geändert worden.
Da gab es ja schon einmal ein Ticket.

Es wäre schon schön, wenn man den Ordner der Quelldateien nutzen könnte, damit man seine Pfade in den Dateien nicht anpassen muss.

**Comment by AWqxKAWERbXo** [comment]
@iceman-fx sorry, dass dir das jetzt auch passiert ist. Kannst du näher beschreiben, wie du minify verwendet hast? War bereits eine ältere Version installiert?

**Comment by AWqxKAWERbXo** [comment]
Für den Fehler: Siehe #48

**Comment by iceman-fx** [comment]
Das Ticket mit dem Fehler habe ich gelesen.
Aber anscheinend besteht das Problem weiterhin.

Bei mir ist es so, dass ich dieses Addon vorher noch nie installiert hatte.
Es wurde zum ersten Mal installiert und genutzt.

Bei den Einstellungen hatte ich /media als Zielordner gewählt und dann ein CSS-Set erstellt.
Der erste Test (ohne Minimierung) klappte auch.
Nach Einschalten der Minim. passierte erst einmal nichts. Kurz Cache geleert und der Fehler kam.
Es stellte sich dann heraus, dass die originalen CSS-Dateien gelöscht waren.

**Comment by AWqxKAWERbXo** [comment]
Danke für die Info!
