### ISSUE TITLE
Fehler, wenn Cache-Verzeichnis nicht erstellbar

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/minify#59]
Es gibt Situationen bei Hostern, da wird bei der Installation von minify kein Cache-Verzeichnis erstellt und dieses ist demzufolge dann auch nicht beschreibbar, weshalb minify nicht funktionieren kann in diesem Moment.

Genauer kann ich das Problem jedoch noch nicht eingrenzen. Hatte den Fall jetzt schon 3-4 Mal.

**Comment by pschuchmann** [comment]
Ich kann es aktuell leider nicht wirklich testen, aber vielleicht löst #69 das Problem. Sobald du Pfade einträgst, sollten sie beim Speichern auch angelegt werden oder eine Fehlermeldung ausgeben.

**Comment by AWqxKAWERbXo** [comment]
Ich nutze das Addon ohnehin nicht mehr.
