### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/minify#6]
Wenn ich die aktuelle Version aus dem Installer aktiviere erhalte ich einen Internal Server Error.
REX 5.2.0

Hat das sonst niemand?

**Comment by staabm** [comment]
irgendwelche fehler im logfile?

**Comment by olien** [comment]
Apache Log:

[Wed Aug 10 13:02:54 2016] [error] [client ::1] FastCGI: incomplete headers (0 bytes) received from server "/Applications/MAMP/fcgi-bin/php5.6.10.fcgi", referer: http://domain/redaxo/index.php?page=install/packages/add&addonkey=minify&rex-api-call=install_package_add&file=1669

Im PHP Log steht nichts

**Comment by phoebusryan** [comment]
Interessant, das ist mir neu und sagt mir so auch gar nichts.

Was steht im Redaxo-Log unter "System"?

**Comment by olien** [comment]
leider nichts....

**Comment by phoebusryan** [comment]
Wurde das Addon denn dennoch installiert oder passiert das nun jedes mal?

**Comment by staabm** [comment]
ich hätte https://github.com/redaxo/redaxo/commit/92cbfc32e4c637da680b6fe37c58a46aac959216 vermutet, allerdings ist dieser fix auch schon in 5.2.0 enthalten..

@gharlan ..?

@phoebusryan ggf. machst du einen ähnlichen "header" fehler in diesem addon?

**Comment by phoebusryan** [comment]
Das Addon sendet eigentlich keine Header, sondern macht lediglich Output-Replacing. 

@olien Welche Version hast du überhaupt installiert? Ist es die 5.2.X?

**Comment by olien** [comment]
REDAXO 5.2.0
PHP 5.6.10

**Comment by staabm** [comment]
welcher Hoster? Problem in allen Browsern? verschwindet das problem wenn minify deaktiviert/deinstalliert ist?

**Comment by olien** [comment]
Mamp - mach aber ansonsten aktuell keine Probleme. Andere Browser = gleiches Ergebnis.

**Comment by staabm** [comment]
ggf. irgendwelche htaccess oder rewrite probleme?

**Comment by staabm** [comment]
@olien schau mal im logfile des apachen

**Comment by olien** [comment]
[Thu Aug 11 09:30:47 2016] [error] [client ::1] FastCGI: incomplete headers (0 bytes) received from server "/Applications/MAMP/fcgi-bin/php5.6.10.fcgi", referer: http://rex5basic2/redaxo/index.php?page=packages

**Comment by olien** [comment]
Hm. Auf dem Rechner zu Hause funktioniert die Installation...

**Comment by olien** [comment]
Nachtrag: Die Umstellung auf PHP 7.0.8 hat das Problem behoben.
