### ISSUE TITLE
Konfigurationsseite: Gleiches Markup wie bei anderen Addons verwenden

### ISSUE THREAD

**Issue by schorschy** [FriendsOfREDAXO/minify#62]
ich verwende custom-styles im backend und der minify-safe-button tanzt aus der reihe. andere addons haben das folgende markup für save-buttons:

`<button id="rex-[addon-name]-save" type="submit" name="config-submit" class="btn btn-save rex-form-aligned" value="1">Einstellungen speichern</button>`

minify benutzt `<input type="submit">`

man müsste zeile 69 in der config.php wie folgt ändern (ungetestet):

`$n['field'] = '<button id="rex-minify-save" type="submit" name="config-submit" value="'.$this->i18n('config_action_save').'" class="btn btn-save rex-form-aligned" '.rex::getAccesskey($this->i18n('config_action_save'), 'save').'>';`

oder man gibt dem input einfach die klassen `btn btn-save` mit.

kann mir jemand bei der gelegenheit erklären, was es damit auf sich hat?
`value="'.$this->i18n('config_action_save').'"`

**Comment by pschuchmann** [comment]
Hey,

ich bin gerade am Basteln und bringe heute nochmal eine neue Version raus. Ich schaue da gleich mal rein.
