### ISSUE TITLE
Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters

### ISSUE THREAD

**Issue by omphteliba** [FriendsOfREDAXO/minify#66]
Den Fehler sehe ich schon seit längerem im System Log:

Typ: Deprecated
Nachricht: implode(): Passing glue string after array is deprecated. Swap the parameters
Datei: redaxo/src/addons/minify/vendor/minify/src/CSS.php
Zeile: 518

Redaxo: 5.10.0
PHP: 7.4.3

**Comment by AWqxKAWERbXo** [comment]
Hast du nachgesehen, ob es ein vendor Update gibt? Oder müssen wir das fixen?

**Comment by omphteliba** [comment]
Ja, es gibt ein vendor Update Version 1.3.63 vom 21.1.2020 in der alle `implodes` die richtige Parameter Reihenfolge haben.

**Comment by AWqxKAWERbXo** [comment]
Scheinbar wurde hier im Repo schon was gemacht - willst du die GitHub-Version mal testen? Vielleicht wurde noch kein release gemacht.

**Comment by omphteliba** [comment]
Die GitHub-Version wirft die Warnung nicht mehr, aber funktioniert weiterhin (HTML zu verkleinern verändert meine Website z.B. noch immer, dafür könnte ich auch mal ein Ticket machen). Ich habe aber nicht großartig getestet, sondern einfach nur das alte Addon gegen die Github Version ausgetauscht.

**Comment by pschuchmann** [comment]
In der GitHub Version ist bereits ein aktuellerer Vendor als derzeit im Installer. Ich checke heute nochmal den Vendor und mach dann ein Release, dass es auch im Installer verfügbar ist.

**Comment by pschuchmann** [comment]
Ist gerade in den Installer gewandert mit dem Vendor Update, ich mache dann erstmal zu.
