### ISSUE TITLE
Cache löschen führt zur Löschung der CSS-Dateien

### ISSUE THREAD

**Issue by erraiva** [FriendsOfREDAXO/minify#67]
Hallo, ich weiß, das wurde hier schon erwähnt, doch für meine Projekte ist das ziemlich schlimm.
Ich habe alle CSS, JS-Dateien in einem eigenen Verzeichnis "resources". Beim Löschen des Minify-Caches werden (zumindest) die CSS Dateien, die ich in den Minify-Sets eingebunden habe, radikal und ohne Vorwarnung gelöscht. Kann ich das vermeiden? Oder, besser: könnte das im Addon geändert werden?
LG Heinz

**Comment by AWqxKAWERbXo** [comment]
Vorübergehende Lösung: Nicht die SCSS/CSS-Quelldateien im selben Ordner haben wie die Cache-Dateien.

**Comment by AWqxKAWERbXo** [comment]
duplicate #48

**Comment by AWqxKAWERbXo** [comment]
Und das kann natürlich im Addon geändert werden, PR welcome.
