### ISSUE TITLE
css einbinden media=xxx

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/minify#7]
Toll wäre es wenn ich dem CSS Link noch ein media="print" / media="screen" mitgeben könnte

LG
Oliver

**Comment by skerbis** [comment]
Dem schließe ich mich an.

**Comment by staabm** [comment]
oder auch einen vollen media-query.

**Comment by phoebusryan** [comment]
Ja, würde ich so machen. Einfach ein Textfeld was übernommen wird. Was da reinkommt ist mir dann egal.

**Comment by staabm** [comment]
fixed via https://github.com/FriendsOfREDAXO/minify/commit/a1698f9dc4e4adcd84385008d241ed0717f077de
