### ISSUE TITLE
v. 2.2. Class 'MatthiasMullie\Minify\CSS' not found

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/minify#70]
Nach Update auf 2.2

**Comment by skerbis** [comment]
**Error:** Class 'MatthiasMullie\Minify\CSS' not found
**File:** redaxo/src/addons/minify/lib/class.minify.php
**Line:** 94

<details>
<summary>Stacktrace</summary>

| Function                     | File                                                 | Line     |
| ---------------------------- | ---------------------------------------------------- | -------- |
| minify->minify               | redaxo/src/addons/minify/boot.php                    | 81       |
| rex_package->{closure}       | redaxo/src/core/lib/extension.php                    | 45       |
| rex_extension::registerPoint | redaxo/src/core/lib/response.php                     | 251      |
| rex_response::sendPage       | redaxo/src/addons/structure/plugins/content/boot.php | 62       |
| rex_package::{closure}       | redaxo/src/core/lib/extension.php                    | 45       |
| rex_extension::registerPoint | redaxo/src/core/frontend.php                         | 26       |
| require                      | redaxo/src/core/boot.php                             | 137      |
| require                      | index.php                                            | 9        |

</details>
<details>
<summary>System report (REDAXO 5.10.1, PHP 7.2.18)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.10.1     |


| PHP           |            |
| ------------: | :--------- |
|       Version | 7.2.18     |
|       OPcache | yes        |
|        Xdebug | no         |


| Database      |                                |
| ------------: | :----------------------------- |
|       Version | MySQL 5.5.62                   |
| Character set | utf8                           |
|       Warning | Die verwendete MySQL Version 5.5.62 wird nicht mehr vom Hersteller gepflegt und sollte aktualisiert werden. |


| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | fpm-fcgi   |
|     Webserver | Apache     |


| Request       |             |
| ------------: | :---------- |
|       Browser | Safari/13.1 |
|      Protocol | HTTP/1.0    |
|         HTTPS | yes         |


| Packages                   |             |
| -------------------------: | :---------- |
|                    adminer | 1.8.1       |
|                     backup | 2.6.0       |
|                   be_style | 2.10.1      |
|        be_style/customizer | 2.10.0      |
|            be_style/redaxo | 2.10.1      |
|                    bloecks | 3.0.0       |
|           bloecks/cutncopy | 3.0.0       |
|          bloecks/dragndrop | 3.0.0       |
|             bloecks/status | 3.0.0       |
|                       cke5 | 3.7.1       |
|                   ckeditor | 4.13.1      |
|                    cronjob | 2.7.0       |
|                    cropper | 1.1.0       |
|                 focuspoint | 2.2.2       |
|                   icecoder | 2.0.1       |
|                    install | 2.7.1       |
|                       iwcc | 1.0.8       |
|                maintenance | 2.2.0       |
|                   markitup | 3.3.4       |
|                     matomo | 1.2.1       |
|                     mblock | 3.1.0       |
|              media_manager | 2.9.1       |
|                  mediapool | 2.8.1       |
|                   metainfo | 2.7.1       |
|                      mform | 5.3.1       |
|                    minibar | 2.0.2       |
|                     minify | 2.2         |
|              modulsammlung | 4.14.0      |
|           navigation_array | 1.0.3       |
|                     pdfout | 2.1.0       |
|                  phpmailer | 2.8.2       |
|                    project | dev         |
|           quick_navigation | 3.7.2       |
|                  search_it | 6.7.2       |
|     search_it/autocomplete | 6.7.2       |
|    search_it/documentation | 6.7.2       |
|        search_it/plaintext | 6.7.2       |
|            search_it/stats | 6.7.2       |
|                simplestats | 1.0.0       |
|                  structure | 2.10.1      |
|          structure/content | 2.10.1      |
|           structure_tweaks | 1.2.0       |
|                   ui_tools | 1.0.0       |
| ui_tools/jquery-minicolors | 2.2.7       |
|                       undo | 2.1.3       |
|                   uploader | 2.0.5       |
|                        url | 2.0.0-beta3 |
|                      users | 2.6.2       |
|                     watson | 2.2.0       |
|                      yform | 3.3.1       |
|                 yform/docs | 3.3.1       |
|                yform/email | 3.3.1       |
|              yform/manager | 3.3.1       |
|                yform/tools | 3.3.1       |
|                   yrewrite | 2.6         |
|            yrewrite_scheme | 3.2.1       |
|                zip_install | 1.1         |

</details>

**Comment by skerbis** [comment]
Bei einem 2. Versuch war alles in Ordnung

**Comment by AWqxKAWERbXo** [comment]
Was heißt zweiter Versuch? Wenn Klassen in der update.php verwendet werden, sind diese noch nicht im Autoloader.

**Comment by skerbis** [comment]
2. Versuch - fast identische Installation update durchgeführt. geht. 
3. Versuch Originalinstallation zurückgesetzt auf vorherigen snapshot, geht
 
Konnte ich also nicht mehr reproduzieren

**Comment by pschuchmann** [comment]
Ich habe das Gefühl, dass sich der Installer aktuell abundzu verschluckt. Hatte einen ähnlichen Effekt mit einer Uralt Version von Minify in der noch ein alter Regex für die Minimierung des HTML drin war. Die Version hab ich bei Update bekommen. Habe das Addon dann gelöscht und die gleiche Version nochmal installiert und dann war alles gut.

Gleiches Spiel mit YRewrite, seit Version 2.5 meine ich liegen die Klassen mittlerweile unter `lib/yrewrite`, ehemals direkt unter `lib`. Bei einem Update hatte ich doppelte Klassen. Ist kaum zu reproduzieren, aber passiert gelegentlich.

**Comment by skerbis** [comment]
Ich mach das hier noch mal auf. Wir sollten das in der Beta von REDAXO 5.11 beobachten und ggf. dann dort ein Issue drauf machen.

**Comment by pschuchmann** [comment]
Den Fall hatte ich jetzt vor Kurzem auch nochmal. Datei war physikalisch da, dauert es möglicherweise einfach etwas bis der Autoloader das alles neu gezogen hat?

**Comment by pschuchmann** [comment]
Gab es hier nochmal Probleme? Ansonsten würde ich das vorerst schließen.
