### ISSUE TITLE
Dateien einzeln minimierbar machen

### ISSUE THREAD

**Issue by danspringer** [FriendsOfREDAXO/minify#72]
Bisher gibt es nur die Möglichkeit **Minimieren? - Ja/Nein** auszuwählen.
Wählt man Ja aus, werden die Dateien komprimiert und gebundelt als eine Datei ausgegeben.

Wählt man die Minimierung nicht aus, werden die Dateien des Sets einzeln und unkomprimiert ausgegeben.

Ich hätte gerne noch die Möglichkeit, die Dateien nicht im Bundle, sondern einzeln, aber jede für sich komprimiert auszugeben.

Sprich eine neue Option **Zusammenfassen?**:

Minimieren sollte auch nur minimieren, nicht bundlen.
Optional dann die Möglichkeit, die Dateien zu einer zu bundlen oder eben nicht.

**Comment by AWqxKAWERbXo** [comment]
Dafür gibt's gzip beim Hoster in der htaccess.

**Comment by iceman-fx** [comment]
Ich schließe mich der Idee von @danspringer an.
Fände es auch gut, wenn man die Option jeweils separat konfigurieren könnte.

Und gzip vom Hoster hat damit nicht direkt etwas zu tun.

**Comment by AWqxKAWERbXo** [comment]
@danspringer ist dein Issue noch aktuell oder kann hier zu?

**Comment by danspringer** [comment]
Da fragst du mich was... ist schon so lange her - ich kann mich nur noch vage an den Fall erinnern.
Aber wenn es mittlerweile nicht umgesetzt wurde, kann man es wohl eh schließen, ja :)
