### ISSUE TITLE
Consider Update vendor Minify Module

### ISSUE THREAD

**Issue by geraldurbas** [FriendsOfREDAXO/minify#73]
**Feature description / Feature Beschreibung**
on PHP 8.2 i get a "Deprecated 	Use of "parent" in callables is deprecated" Message
minify/vendor/matthiasmullie/minify/src/JS.php

Saw the used latest version of minify Library fix it
> https://github.com/matthiasmullie/minify

**Comment by AWqxKAWERbXo** [comment]
@geraldurbas würdest du gerne dafür einen PR vorbereiten?

**Comment by geraldurbas** [comment]
Ich mag nichts versprechen, das sich zeitlich nicht ausgeht. Falls ich damit anfangen kann, geb ich Bescheid.
