### ISSUE TITLE
Wunsch: Minifizierung von HTML

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/minify#8]

**Comment by AWqxKAWERbXo** [comment]
ich habe mit XOutputFilter in R4 eine sehr simpel strukturierte Minifzierung vorgenommen.

Zeilenumbrüche `/[\n]+/` ersetzen mit ` `
Kommentare`/<!-- .*? -->/ms`ersetzen mit` `
und doppelte oder mehr Leerzeichen`/\s\s+/`ersetzen mit` `

Aber @phoebusryan hat da bestimmt was besseres auf Lager.

**Comment by olien** [comment]
Ähnliches hab ich in dem out5 plugin....

**Comment by phoebusryan** [comment]
Ich frage mich gerade, wie ich das lösen soll. Will man das immer aktiv haben? Soll das ein-/ausschaltbar sein? Soll es ein Plugin sein? hm..

**Comment by olien** [comment]
Als Plugin würde ich es nicht machen. Gehört ja zum Thema.
Ein- / Ausschaltbar fänd ich wichtig gut (evtl. neues Tab "HTML").

Ich hab das in out5 so gemacht:
https://github.com/FriendsOfREDAXO/out5/blob/master/plugins/min/boot.php

Aber das kann ja dann wech :-)

**Comment by phoebusryan** [comment]
Okay gut. Dann einen extra Tab mit Einstellungen.
