### ISSUE TITLE
html minification vs inline js kommentar

### ISSUE THREAD

**Issue by IngoWinter** [FriendsOfREDAXO/minify#9]
habe ich nen javascript block mit einem einzeiligen kommentar via `//` ist die fee am arsch...
abgesehen davon scheints noch ne menge mehr dinge zu geben, die kaputtgehen können.

http://stackoverflow.com/questions/5312349/minifying-final-html-output-using-regular-expressions-with-codeigniter
https://gist.github.com/tovic/d7b310dea3b33e4732c0

**Comment by phoebusryan** [comment]
Sofern Inline JS existiert, und nicht über das Addon eingespeist wird, ja. Das Problem hatten wir grade am Freitag auch bei Thomas Skerbis.
